/*Copyright (c) 2015-2016 imaginea-com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea-com*/
package com.passportapp.passportapp;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ApplicantDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ApplicantDetails`")
public class ApplicantDetails implements Serializable {

    private Integer id;
    private String applicantGivenName;
    private String applicationType;
    private Integer passportBookeltsize;
    private String applyingfor;
    private String applicantSurName;
    private String gender;
    private Date dob;
    private String reissueReason;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`ApplicantGivenName`", nullable = false, length = 55)
    public String getApplicantGivenName() {
        return this.applicantGivenName;
    }

    public void setApplicantGivenName(String applicantGivenName) {
        this.applicantGivenName = applicantGivenName;
    }

    @Column(name = "`ApplicationType`", nullable = false, length = 255)
    public String getApplicationType() {
        return this.applicationType;
    }

    public void setApplicationType(String applicationType) {
        this.applicationType = applicationType;
    }

    @Column(name = "`PassportBookeltsize`", nullable = true, scale = 0, precision = 10)
    public Integer getPassportBookeltsize() {
        return this.passportBookeltsize;
    }

    public void setPassportBookeltsize(Integer passportBookeltsize) {
        this.passportBookeltsize = passportBookeltsize;
    }

    @Column(name = "`Applyingfor`", nullable = true, length = 255)
    public String getApplyingfor() {
        return this.applyingfor;
    }

    public void setApplyingfor(String applyingfor) {
        this.applyingfor = applyingfor;
    }

    @Column(name = "`ApplicantSurName`", nullable = false, length = 45)
    public String getApplicantSurName() {
        return this.applicantSurName;
    }

    public void setApplicantSurName(String applicantSurName) {
        this.applicantSurName = applicantSurName;
    }

    @Column(name = "`Gender`", nullable = false, length = 20)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "`DOB`", nullable = false)
    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    @Column(name = "`ReissueReason`", nullable = true, length = 80)
    public String getReissueReason() {
        return this.reissueReason;
    }

    public void setReissueReason(String reissueReason) {
        this.reissueReason = reissueReason;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ApplicantDetails)) return false;
        final ApplicantDetails applicantDetails = (ApplicantDetails) o;
        return Objects.equals(getId(), applicantDetails.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

