/*Copyright (c) 2015-2016 imaginea-com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea-com*/
package com.passportapp.passportapp.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.passportapp.passportapp.ApplicantDetails;

/**
 * Service object for domain model class {@link ApplicantDetails}.
 */
public interface ApplicantDetailsService {

    /**
     * Creates a new ApplicantDetails. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ApplicantDetails if any.
     *
     * @param applicantDetails Details of the ApplicantDetails to be created; value cannot be null.
     * @return The newly created ApplicantDetails.
     */
	ApplicantDetails create(ApplicantDetails applicantDetails);


	/**
	 * Returns ApplicantDetails by given id if exists.
	 *
	 * @param applicantdetailsId The id of the ApplicantDetails to get; value cannot be null.
	 * @return ApplicantDetails associated with the given applicantdetailsId.
     * @throws EntityNotFoundException If no ApplicantDetails is found.
	 */
	ApplicantDetails getById(Integer applicantdetailsId) throws EntityNotFoundException;

    /**
	 * Find and return the ApplicantDetails by given id if exists, returns null otherwise.
	 *
	 * @param applicantdetailsId The id of the ApplicantDetails to get; value cannot be null.
	 * @return ApplicantDetails associated with the given applicantdetailsId.
	 */
	ApplicantDetails findById(Integer applicantdetailsId);


	/**
	 * Updates the details of an existing ApplicantDetails. It replaces all fields of the existing ApplicantDetails with the given applicantDetails.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on ApplicantDetails if any.
     *
	 * @param applicantDetails The details of the ApplicantDetails to be updated; value cannot be null.
	 * @return The updated ApplicantDetails.
	 * @throws EntityNotFoundException if no ApplicantDetails is found with given input.
	 */
	ApplicantDetails update(ApplicantDetails applicantDetails) throws EntityNotFoundException;

    /**
	 * Deletes an existing ApplicantDetails with the given id.
	 *
	 * @param applicantdetailsId The id of the ApplicantDetails to be deleted; value cannot be null.
	 * @return The deleted ApplicantDetails.
	 * @throws EntityNotFoundException if no ApplicantDetails found with the given id.
	 */
	ApplicantDetails delete(Integer applicantdetailsId) throws EntityNotFoundException;

	/**
	 * Find all ApplicantDetails matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ApplicantDetails.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<ApplicantDetails> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all ApplicantDetails matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ApplicantDetails.
     *
     * @see Pageable
     * @see Page
	 */
    Page<ApplicantDetails> findAll(String query, Pageable pageable);

    /**
	 * Exports all ApplicantDetails matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the ApplicantDetails in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the ApplicantDetails.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

